import { collection, query, orderBy, getDocs, doc, getDoc } from "firebase/firestore";
import { getServerDb } from "../../../../../lib/firebase-admin";

export async function POST(req) {
  try {
    const { roomId } = await req.json();
    const db = getServerDb();

    if (!roomId) {
      return Response.json(
        { error: "roomId is required" },
        { status: 400 }
      );
    }

    // Fetch room data
    const roomDoc = await getDoc(doc(db, "rooms", roomId));
    const roomData = roomDoc.exists ? roomDoc.data() : {};
    const title = roomData.title || "Collaboration Room";
    const language = roomData.language || "Not specified";

    // Fetch messages
    const messagesRef = collection(db, "rooms", roomId, "messages");
    const messagesQuery = query(messagesRef, orderBy("createdAt", "asc"));
    const messagesSnap = await getDocs(messagesQuery);
    const messages = messagesSnap.docs.map(d => ({ id: d.id, ...d.data() }));

    // Fetch notes
    const noteContent = roomData.noteContent || "";

    const messagesText = messages.length > 0
      ? messages.map(m => `- ${m.senderName || "Anonymous"} (${m.createdAt ? new Date(m.createdAt.toDate()).toLocaleDateString() : "recent"}): ${m.text}`).join("\n")
      : "No messages yet.";

    const notesText = noteContent ? noteContent : "No notes yet.";

    const sarvamApiKey = process.env.SARVAM_API_KEY;

    if (!sarvamApiKey) {
      const fallbackSummary = [
        `## ${title || "Collaboration Room"} Summary`,
        "",
        `**Room ID**: ${roomId || "N/A"}`,
        `**Language**: ${language || "Not specified"}`,
        `**Generated**: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`,
        "",
        "---",
        "",
        "### Recent Messages",
        messagesText,
        "",
        "### Recent Notes",
        notesText,
        "",
        "---",
        "",
        `_Generated by DevConnect AI • ${new Date().toLocaleDateString()}_`,
      ].join("\n");

      return Response.json({
        summary: fallbackSummary,
        hasApiKey: false,
        suggestion: "Configure SARVAM_API_KEY for AI-powered summaries",
        messageCount: messages.length,
        noteCount: noteContent ? 1 : 0,
      });
    }

    const systemPrompt = [
      "You are an AI assistant that creates concise collaboration room summaries.",
      "Analyze the conversation and notes provided and generate a summary that:",
      "- Captures key discussion points and decisions",
      "- Highlights important code snippets or technical discoveries",
      "- Lists action items or next steps",
      "- Uses markdown formatting for readability",
      "Keep the summary focused and actionable. Do not add fluff.",
    ].join(" ");

    const userPrompt = [
      `Room: ${title || "Untitled"}`,
      `Language: ${language || "Not specified"}`,
      "",
      "Recent Messages:",
      messagesText,
      "",
      "Recent Notes:",
      notesText,
      "",
      "Please provide a comprehensive room summary.",
    ].join("\n");

    const sarvamResponse = await fetch("https://api.sarvam.ai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "api-subscription-key": sarvamApiKey,
      },
      body: JSON.stringify({
        model: "sarvam-30b",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.3,
        max_tokens: 1500,
      }),
    });

    if (!sarvamResponse.ok) {
      const errText = await sarvamResponse.text();
      console.error("Sarvam AI API error:", errText);
      return Response.json(
        { error: "Failed to generate AI summary", details: errText },
        { status: 500 }
      );
    }

    const data = await sarvamResponse.json();
    const summaryBody = data.choices?.[0]?.message?.content || "";

    const formattedSummary = [
      `## ${title || "Collaboration Room"} Summary`,
      "",
      `**Room ID**: ${roomId || "N/A"}`,
      `**Language**: ${language || "Not specified"}`,
      `**Generated**: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`,
      "",
      "---",
      "",
      summaryBody,
      "",
      "---",
      "",
      `_Generated by DevConnect AI • ${new Date().toLocaleDateString()}_`,
    ].join("\n");

    return Response.json({
      summary: formattedSummary,
      hasApiKey: true,
      messageCount: messages.length,
      noteCount: noteContent ? 1 : 0,
    });

  } catch (error) {
    console.error("Error generating room summary:", error);
    return Response.json(
      { error: "Failed to generate room summary", details: error.message },
      { status: 500 }
    );
  }
}